### ISSUE TITLE
Unable to sample from anything but small datasets

### ISSUE THREAD

**Issue by brockf** [goldingn/greta#60] opened 2017-05-13 22:34 UTC
I'm having trouble sampling from models with any moderate amount of data. I was working with a real dataset today and couldn't get anything to work — every sample was rejected. I started to have a hunch that it was a problem with the data, so I began to work with random, normally-distributed data.

When I generated a small dataset (N=100), everything works fine:

```
# define data
y = as_data(rnorm(100,10,1))
x = as_data(rnorm(100,10,1))

# define parameters
intercept = normal(10,10)
coefficient = normal(0,10)
sd = lognormal(0,1)

# define model
mean <- intercept + coefficient * x

# define the likelihood of the observed data
distribution(y) = normal(mean, sd)

# sample from model
greta_model <- define_model(intercept, coefficient)
draws <- mcmc(greta_model, n_samples = 1000, warmup=100)

# evaluate model
summary(draws)

MCMCtrace(draws)
MCMCplot(draws)
```

But if I change the distributions to have 10,000 samples each, every sample is rejected during `mcmc()` and the posterior is invariant:

```
# define data
y = as_data(rnorm(10000,10,1))
x = as_data(rnorm(10000,10,1))
...
```

Any ideas about what might be causing this problem?

**Comment by goldingn** [comment] 2017-05-14 00:41
Hi Brock, thanks for trying out greta and for the feedback!

So far I've only implemented 'vanilla' Hamiltonian Monte Carlo, which requires manual* tuning of hyperparameters. The leapfrog step length 'epsilon' is the key thing to tune, and can be set via the `control` argument to `mcmc()`, like this:

```r
mcmc(..., control = list(epsilon = 0.005)
```

In general the more data, the more extreme the density surface to explore, so a smaller epsilon will lead to higher acceptance rates. For the model above, this works well for me (no rejections):

```r
draws <- mcmc(greta_model, n_samples = 1000, warmup=100,
              control = list(epsilon = 0.0001))
```

In the longer term, I plan to hook STAN's samplers into greta, and their implementation of NUTS seems to do a great job of avoiding this issue of manually tuning the sampler. I'll keep vanilla HMC as an option, since [there are circumstances when it's more efficient](https://radfordneal.wordpress.com/2012/01/27/evaluation-of-nuts-more-comments-on-the-paper-by-hoffman-and-gelman/).

In the short term, I now realise there's no documentation of these control parameters in the `mcmc()`, so I'll fix that right away. I'll mention of the need to think about tuning epsilon.

I hope this helps for your model, I'd be interested hear what you're using greta for!

---

* actually the sampler tries to optimise epsilon starting from the value specified in control, but it relies on a good starting value

**Comment by goldingn** [comment] 2017-05-14 13:52
I fixed the docs on master in #61, so closing this now. Please reopen if the issue isn't fixed for you

**Closed by goldingn** 2017-05-14 13:52 UTC

**Comment by goldingn** [comment] 2017-05-22 12:48
Hi @brockf,

I just realised I had never merged the self-tuning HMC sampler into the current version of greta, it was languishing in a fork somewhere.

I've just merged it into the dev branch, so you can install it with:
```r
devtools::install_github(‘goldingn/greta@dev')
```
Running your example with this version, it has no problem sampling, and converges quite nicely.

One thing to bear in mind it that when there's lots of data, it becomes quite important to provide reasonable initial values. That's because the parameters are very strongly identified (little uncertainty) so the initial conditions can have very low density, leading to rejected samples.

If you still have convergence problems with the new sample, that might be worth a try.

Happy to help if that doesn't work though!

**Comment by brockf** [comment] 2017-05-22 15:48
Thanks, @goldingn ! Appreciate the follow-up :)
